#!/usr/bin/env python3
"""Generate explicit singular inflections for selected TERYT city names.

All one-token official cities get a canonical nominative entry in the source
layer. Full singular inflection is generated for:
  * the top N cities by wordfreq Polish frequency;
  * explicit project-priority cities in a reviewed TSV;
  * every official city name containing a project-recognized lexical hyphen, using a city-specific aligned-case model.

Only forms generated by Morfeusz 2 / SGJP are emitted.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import re

from surface_components import HYPHEN_SPLIT_RE, hyphen_components, is_hyphenated

CASES = ("nom", "gen", "dat", "acc", "inst", "loc", "voc")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cities", type=Path, required=True)
    ap.add_argument("--priorities", type=Path, required=True)
    ap.add_argument("--top-n", type=int, default=300)
    ap.add_argument("--overrides", type=Path, default=None)
    ap.add_argument("--out-tsv", type=Path, required=True)
    ap.add_argument("--out-report", type=Path, required=True)
    return ap.parse_args()


def load_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def case_from_tag(tag: str) -> set[str]:
    parts = tag.split(":")
    if len(parts) < 3 or parts[0] != "subst" or parts[1] != "sg":
        return set()
    return {c for c in parts[2].split(".") if c in CASES}


def case_forms_for_component(morfeusz, component: str) -> dict[str, set[str]]:
    """Return SGJP-backed forms grouped by grammatical case for one component."""
    out: dict[str, set[str]] = {case: set() for case in CASES}
    lower = component.lower()
    for lemma_query in (component, lower):
        for orth, lemma, tag, _names, _labels in morfeusz.generate(lemma_query):
            if str(lemma).lower() != lower:
                continue
            parts = str(tag).split(":")
            if len(parts) < 3 or parts[1] not in {"sg", "pl"}:
                continue
            for case in {value for value in parts[2].split(".") if value in CASES}:
                surface = str(orth).strip()
                if surface and re.fullmatch(r"^[A-Za-ząćęłńóśźżĄĆĘŁŃÓŚŹŻ]+$", surface):
                    out[case].add(surface[:1].upper() + surface[1:])
    return out


def build_hyphenated_city_forms(morfeusz, name: str) -> set[tuple[str, str]]:
    """Build aligned-case full city forms while preserving the source hyphen."""
    parts = hyphen_components(name)
    separators = HYPHEN_SPLIT_RE.findall(name)
    if len(parts) < 2 or len(separators) != len(parts) - 1:
        return set()

    component_forms = [case_forms_for_component(morfeusz, part) for part in parts]

    def preserve_source_initial(value: str, source_part: str) -> str:
        if not value:
            return value
        if source_part[:1].isupper():
            return value[:1].upper() + value[1:]
        return value[:1].lower() + value[1:]

    out: set[tuple[str, str]] = set()
    for case in CASES:
        choices = [
            sorted(
                preserve_source_initial(value, part)
                for value in forms[case]
            )
            for part, forms in zip(parts, component_forms)
        ]
        if not all(choices):
            continue
        # Deterministic, bounded Cartesian product. For official city names
        # component ambiguity is uncommon; the cap prevents pathological oracle output.
        products = [()]
        for values in choices:
            next_products = []
            for prefix in products:
                for value in values[:4]:
                    next_products.append(prefix + (value,))
            products = next_products[:64]
        for product in products:
            full = product[0]
            for separator, value in zip(separators, product[1:]):
                full += separator + value
            if full.lower() != name.lower() or case != "nom":
                out.add((case, full))
    return out


def main() -> int:
    args = parse_args()
    all_cities = load_tsv(args.cities)
    one_token_cities = [
        row for row in all_cities
        if re.fullmatch(r"^[a-ząćęłńóśźż]+$", row["name"], re.IGNORECASE)
    ]
    hyphenated_cities = [
        row for row in all_cities
        if is_hyphenated(row["name"].strip())
    ]
    priorities = {row["name"].strip().lower() for row in load_tsv(args.priorities) if row.get("name", "").strip()}
    if not one_token_cities and not hyphenated_cities:
        raise SystemExit("No cities supplied")

    from wordfreq import zipf_frequency
    ranked = sorted(
        one_token_cities,
        key=lambda row: (-float(zipf_frequency(row["name"], "pl")), row["name"].lower()),
    )

    selected = {row["name"].lower() for row in ranked[:args.top_n]}
    selected |= priorities
    selected |= {row["name"].lower() for row in hyphenated_cities}

    import morfeusz2
    from polish_inflection import (
        MIANOWNIK,
        DOPEŁNIACZ,
        CELOWNIK,
        BIERNIK,
        NARZĘDNIK,
        MIEJSCOWNIK,
        WOŁACZ,
        POJEDYNCZA,
        odmien_warianty,
        podaj,
    )

    case_constants = {
        "nom": MIANOWNIK,
        "gen": DOPEŁNIACZ,
        "dat": CELOWNIK,
        "acc": BIERNIK,
        "inst": NARZĘDNIK,
        "loc": MIEJSCOWNIK,
        "voc": WOŁACZ,
    }

    city_meta = {row["name"].lower(): row for row in all_cities}
    overrides: dict[tuple[str, str], dict[str, str]] = {}
    if args.overrides:
        override_rows = load_tsv(args.overrides)
        required = {"city", "case", "form", "source", "basis", "note"}
        for line_no, row in enumerate(override_rows, 2):
            if set(row) != required:
                raise SystemExit(f"Malformed city inflection override row {args.overrides}:{line_no}")
            city = row["city"].strip().lower()
            case_tag = row["case"].strip()
            form = row["form"].strip()
            if case_tag not in CASES or not city or not form or not row["source"].strip() or not row["basis"].strip() or not row["note"].strip():
                raise SystemExit(f"Malformed city inflection override row {args.overrides}:{line_no}")
            if city not in city_meta:
                raise SystemExit(f"City override not present in TERYT source: {row['city']}")
            key = (city, case_tag)
            prior = overrides.get(key)
            if prior and prior["form"] != form:
                raise SystemExit(
                    f"Conflicting city inflection override {args.overrides}:{line_no}: "
                    f"{prior['form']!r} vs {form!r}"
                )
            overrides[key] = dict(row)

    morfeusz = morfeusz2.Morfeusz(
        expand_tags=True,
        expand_dot=True,
        expand_underscore=True,
    )

    out: list[dict[str, str]] = []
    missing_nom: list[str] = []

    for lower_name in sorted(selected):
        meta = city_meta.get(lower_name)
        if meta is None:
            raise SystemExit(f"Priority city not found in TERYT city source: {lower_name}")
        name = meta["name"]
        generated: set[tuple[str, str]] = set()

        # TERYT/SIMC is the authoritative source for the nominative city surface.
        # Morfeusz/SGJP is used only to add attested non-nominative singular forms.
        generated.add(("nom", name))

        # Primary oracle: Morfeusz 2 / SGJP.
        # Hyphenated city names use the dedicated category model below. Running
        # the ordinary full-name generator first can yield malformed partial
        # surfaces such as "-Bielska", so the generic path is limited to
        # one-token city lemmas.
        if not is_hyphenated(name):
            for lemma_query in (name, lower_name):
                for orth, lemma, tag, _names, _labels in morfeusz.generate(lemma_query):
                    if str(lemma).lower() != lower_name:
                        continue
                    if not tag.startswith("subst:sg:"):
                        continue
                    for case_tag in sorted(case_from_tag(tag)):
                        surface = str(orth).strip()
                        if not surface:
                            continue
                        surface = surface[:1].upper() + surface[1:]
                        generated.add((case_tag, surface))

        # For lexical-hyphen city names, preserve the full surface and add
        # aligned same-case component inflections. This is a city-category
        # grammatical model, not a generic rule for every hyphenated name.
        if is_hyphenated(name):
            generated |= build_hyphenated_city_forms(morfeusz, name)

        # Secondary oracle: data-only SGJP index. Reverse-validation prevents a
        # coincidental form from another lemma from entering the city layer.
        if not is_hyphenated(name):
            for case_tag, case_const in case_constants.items():
                if case_tag == "nom":
                    continue
                try:
                    variants = list(odmien_warianty(lower_name, case_const, POJEDYNCZA))
                except Exception:
                    variants = []
                for variant in variants:
                    form = str(variant).strip()
                    if not form:
                        continue
                    analyses = podaj(form, liczba=POJEDYNCZA)
                    valid = any(
                        str(analysis.lemat).lower() == lower_name
                        and str(analysis.przypadek) == case_tag
                        and str(analysis.liczba) == "sg"
                        for analysis in analyses
                    )
                    if valid:
                        generated.add((case_tag, form[:1].upper() + form[1:]))

        # Reviewed overrides cover attested city forms missing from the proper-name
        # oracle. They are source-backed and auditable; they never create a new city.
        for (override_city, case_tag), row in overrides.items():
            if override_city != lower_name:
                continue
            generated.add((case_tag, row["form"].strip()))

        for case_tag, surface in sorted(generated, key=lambda item: (CASES.index(item[0]), item[1])):
            override = overrides.get((lower_name, case_tag))
            out.append({
                "name": name,
                "gender": "",
                "layer": "city",
                "case": case_tag,
                "form": surface,
                "source": override["source"] if override else "Morfeusz 2 / SGJP generated from GUS TERYT SIMC city lemma",
                "morfeusz_version": str(morfeusz2.__version__),
            })

    # Nominative forms come directly from TERYT; therefore a city is valid even when
    # Morfeusz does not classify its proper-name lemma. Non-nominative forms remain
    # oracle-backed and are simply absent when SGJP has no analyzed form.

    with args.out_tsv.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["name", "gender", "layer", "case", "form", "source", "morfeusz_version"],
            delimiter="\t",
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(out)

    coverage = {}
    for row in out:
        coverage.setdefault(row["name"], set()).add(row["case"])

    report = {
        "oracle": "Morfeusz 2 / SGJP",
        "morfeusz_version": str(morfeusz2.__version__),
        "all_city_names_in_source": len(all_cities),
        "all_one_token_city_names": len(one_token_cities),
        "hyphenated_city_names_selected": len(hyphenated_cities),
        "multi_component_city_names_not_selected_for_non_hyphen_inflection": sum(
            1 for row in all_cities
            if not is_hyphenated(row["name"].strip())
            and not re.fullmatch(r"^[a-ząćęłńóśźż]+$", row["name"], re.IGNORECASE)
        ),
        "top_n": args.top_n,
        "priority_names": sorted(priorities),
        "selected_city_names": len(selected),
        "inflection_record_count": len(out),
        "case_counts": {
            case: sum(1 for row in out if row["case"] == case)
            for case in CASES
        },
        "names_with_non_nominative": sum(
            1 for cases in coverage.values() if len(cases) > 1
        ),
    }
    args.out_report.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
